### ISSUE TITLE
old python2 code

### ISSUE THREAD

**Issue by x4x** [deadsy/py_linenoise#3]
im using python3 and run in to the issue that raw_input() is now input(). (see.: https://docs.python.org/3/whatsnew/3.0.html#builtins)

https://github.com/deadsy/py_linenoise/blob/01482f6f7cf48fa74dd6c96de24f8d956a8076b0/linenoise.py#L673

i would suggest a fork for a python3 version.

**Comment by deadsy** [comment]
Fixed. If you are actually hitting this you are running an unsupported terminal (look at your TERM environment variable). Functionality will be limited if you don't have a supported terminal.
